spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cheguanjia
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
system:
  seach:
    key: 95f4ce6a6f1c2e836fed27c22cc259f7



